Add members, methods and imports to EnumDeclarations
Fraunhofer-AISEC/cpg pull request #1450
Opened 2024-03-08 16:03 UTC by robinmaisch

Concerning #1445:

- `EnumDeclaration`s now get assigned their class members, just like `RecordDeclaration`s.
- The `ImportResolver` correctly identifies entries and other members of `EnumDeclaration`s that are imported.
- combined the processing of static and non-static `ImportDeclaration`s, separating them afterwards by `isStatic` (a comment indicated that something similar was done earlier and then undone)
- in some cases re-merged the processing of `EnumDeclaration`s and `RecordDeclaration`s and refactored out common parts into separate methods
- added a test and test files for the above changes

2024-03-11 08:25 UTC, konradweiss requested changes
Overall I like it and would merge it after the names are changed to avoid conflicts with our more restrictive understanding of a `handler`. And it is necessary to resolve the conflicts in the FrontendTest file. Thanks already for you contributions so far!

2024-03-11 08:25 UTC, konradweiss commented on cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.kt
> +    private fun handleInnerRecord(recordDeclaration: RecordDeclaration) {
Here, we should avoid naming the function `handler` as that is our convention for functions that get an AST object from a parser and return an AST object in our CPG representation. Handlers are also added to a handler map in the init block. Here, I would ask for a descriptive name that does not collide with `handler`, e.g. resolve, process, add, etc.

2024-03-11 08:25 UTC, konradweiss commented on cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.kt
> +    private fun <T : TypeDeclaration<T>> handleRecordMembers(
Same here

2024-03-11 08:25 UTC, konradweiss commented on cpg-language-java/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/java/DeclarationHandler.kt
> +    private fun handleImportDeclarations(recordDeclaration: RecordDeclaration) {
And here

2024-03-13 15:30 UTC, robinmaisch commented
Sorry, my IDE reformatted the code back upon committing. And the commit title was not meant to refer to that issue.

2024-03-13 15:50 UTC, konradweiss commented
> Sorry, my IDE reformatted the code back upon committing. And the commit title was not meant to refer to that issue.

It confused me a bit ;)

2024-03-13 19:08 UTC, merged