improve cxx
Fraunhofer-AISEC/cpg pull request #1482
Opened 2024-03-29 09:05 UTC by oxisto

- **Fixing record declaration inference for pointer types.**
- **Extracted tests that really need neo4j in extra class**
- **Remove randomness in EOG starters**
- **C++ improvements to make actual libraries be parsed**
- **Handling destructors better**
- **Fixing destructor**
- **Print statistics**
- **Adding support for && operators**

2024-04-13 15:15 UTC, oxisto commented on cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationManager.kt
> +        // Print some graph statistics
This should be moved to our internal application

2024-04-13 15:15 UTC, oxisto commented on cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/TranslationContext.kt
> +    var inferredFunctions: Int = 0,
not needed because we can just count inferred nodes at the end, should be removed

2024-04-23 09:04 UTC, konradweiss requested changes

2024-04-24 06:37 UTC, konradweiss approved these changes

2024-04-24 06:51 UTC, merged