Made build K2 ready
Fraunhofer-AISEC/cpg pull request #1564
Opened 2024-05-22 07:59 UTC by oxisto

2024-06-07 18:20 UTC, KuechA requested changes

2024-06-07 18:20 UTC, KuechA commented on cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt
> -            if (writtenDeclaration != null && lhs != null) {
Not sure why this change is here

2024-06-13 08:22 UTC, konradweiss commented on cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt
> -            if (writtenDeclaration != null && lhs != null) {
lhs != null can be inferred now

2024-06-13 08:22 UTC, KuechA approved these changes

2024-06-13 09:45 UTC, merged