Create one `Type` object per type reference
Fraunhofer-AISEC/cpg pull request #1773
Opened 2024-10-02 23:09 UTC by oxisto

Fixes #1768
Fixes #1770

2024-11-21 10:12 UTC, konradweiss requested changes
I did not encounter any specific issues, however I would like to get the test  coverage up if possible with meaningful tests. We should also look into how these changes impact performance

2024-11-28 21:53 UTC, oxisto commented
> I did not encounter any specific issues, however I would like to get the test coverage up if possible with meaningful tests. We should also look into how these changes impact performance

The missing coverage is mostly due to the low coverage in the DFG function summaries, which I needed to change because of a rename and this drags into bad patch coverage :(

2024-11-28 22:23 UTC, oxisto commented
> I did not encounter any specific issues, however I would like to get the test coverage up if possible with meaningful tests. We should also look into how these changes impact performance

It's faster. 150s vs 200s on the nova benchmark

2024-12-02 12:19 UTC, konradweiss approved these changes

2024-12-02 12:30 UTC, merged